# Generated by Django 5.1 on 2024-09-11 11:46

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('extPosId', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=100, null=True, unique=True)),
                ('username', models.CharField(max_length=100, null=True, unique=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('mobile', models.CharField(max_length=100, null=True)),
                ('gender', models.IntegerField(choices=[(1, 'MALE'), (2, 'FEMALE'), (3, 'OTHER')], null=True)),
                ('profile_pic', models.ImageField(default='users_profile_pics/default-user-icon.jpg', null=True, upload_to='users_profile_pics/')),
                ('address', models.CharField(max_length=250, null=True)),
                ('membership', models.IntegerField(null=True)),
                ('points', models.IntegerField(null=True)),
                ('role', models.IntegerField(choices=[(1, 'SUPER_ADMIN'), (2, 'ADMIN'), (3, 'CUSTOMER')], default=3)),
                ('status', models.IntegerField(choices=[(1, 'ACTIVE'), (2, 'PENDING'), (3, 'INACTIVE'), (4, 'DELETED')], default=1)),
                ('totp_key', models.CharField(max_length=128, null=True)),
                ('is_first_login', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('roles', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'auth_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=255, unique=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('cover', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True, null=True)),
                ('operating_hours', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('zip', models.CharField(max_length=10)),
                ('discount_code', models.CharField(blank=True, max_length=50, null=True)),
                ('discount_message', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='business/logos/')),
                ('images', models.TextField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('socials', models.JSONField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communityapp.business')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communityapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='TagBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communityapp.business')),
            ],
        ),
    ]
