# Generated by Django 5.1 on 2024-09-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='approved',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected')], default=0),
        ),
    ]
