# Generated by Django 5.1 on 2024-09-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityapp', '0007_category_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='isFeatured',
            field=models.BooleanField(default=False),
        ),
    ]
